config/routes.rb
  Swirlysurvey::Application.routes.draw do
  

  root :to => "survey_templates#index", :format => false

  
  resources :survey_templates
  resources :submissions

  match 'survey/login', :to => "survey_templates#login", :format => false, :as => :survey_login

  match 'admin', :to => 'dashboard#index', :format => false, :as => :dashboard
  match 'admin/add_user', :to => 'dashboard#add_user', :format => false, :as => :admin_add_user
  match 'admin/update_permissions', :to => 'dashboard#update_permissions', :format => false, :as => :admin_update_permissions

  match 'admin/login', :to => 'dashboard#login', :format => false, :as => :dashboard_login
  match 'student/login', :to => 'student#login', :format => false, :as => :student_login

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'signout'

end

app/models/admin.rb
class Admin < User

end

app/models/checkbox_field.rb
class CheckboxField < SurveyField

end

app/models/drop_down_field.rb
class DropDownField < SurveyField

end

app/models/email_field.rb
class EmailField < SurveyField
  def is_valid?(response)
  	output = {:value => true}
    if not EmailValidator.valid?(response)
      output[:value] = false
      output[:survey_field] = :email
      output[:message] = "is not valid email"
    end
    output
  end
end

app/models/field_response.rb
class FieldResponse < ActiveRecord::Base
  attr_accessible :response
  belongs_to :survey_field
  belongs_to :submission

  validate :response_format

  def response_format
  	valid_output = self.survey_field.is_valid?(self.response)
    if not valid_output[:value]
      errors.add(valid_output[:survey_field], valid_output[:message])
    end
  end
end

app/models/name_field.rb
class NameField < SurveyField

end

app/models/phone_field.rb
class PhoneField < SurveyField
  def is_valid?(response)
    seven = /^(?:\(?([0-9]{3})\)?[-. ]?)?([0-9]{3})[-. ]?([0-9]{4})$/
    one = /^(?:\+?1[-. ]?)?\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/
    ten = /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/ 
    empty = /^$/
    output = {:value => true}
    if not (response =~ seven or response =~ one or response =~ ten or response =~ empty)
      output[:value] = false
      output[:survey_field] = :phone
      output[:message] = "is not a valid phone number"
    end
    output
  end
end

app/models/radio_button_field.rb
class RadioButtonField < SurveyField

  attr_accessible :radio_button_options
end

app/models/student_response.rb
class StudentResponse < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :email
  belongs_to :survey_template
end

app/models/student_responses.rb
class StudentResponse < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :email
  belongs_to :survey_template
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  has_many :field_responses
  belongs_to :survey_template
end

app/models/submissions.rb
class Submissions < ActiveRecord::Base
	belongs_to: SuveyTemplate
	has_many: FieldResponses through SurveyField
end

app/models/survey_field.rb
class SurveyField < ActiveRecord::Base
  attr_accessible :question_title
  belongs_to :survey_template
  has_many :field_responses
  def is_valid? (response)
    {:value => true}
  end
end

app/models/survey_template.rb
class SurveyTemplate < ActiveRecord::Base
  has_many :survey_fields
  #has_many :name_fields
  has_many :checkbox_fields
  has_many :phone_fields
  has_many :drop_down_fields
  has_many :text_question_fields
  has_many :radio_button_fields
  has_many :email_fields
  has_many :submissions
  has_many :student_responses

end

app/models/text_question_field.rb
class TextQuestionField < SurveyField
  def is_valid? (response)
    {:value => true}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
         # :recoverable, :rememberable, :trackable, :validatable
         # :omniauthable, :omniauth_providers => [:]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin
  attr_accessible :firstname, :lastname, :username, :phone_number, :email, :password, :active, :admin

  def surveyTemplates #This is a dev stub, remove when user is associated with SurveyTemplates
    SurveyTemplate.all
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.email = auth.info.email
      user.save!
    end
  end

end

app/models/volunteer.rb
class Volunteer < User
	#has_many: submissions
end

app/controllers/student_controller.rb
class StudentController < ApplicationController

	def login
	  render :action => "login", :layout => "volunteer_login"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if session[:user_id] %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', dashboard_login_path %></li>
<% end %>

app/views/layouts/admin_login.haml
!!! 5
%html
  %head
    %title DK Tracker Dashboard
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags


    #main
      = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/dashboard.html.haml
!!! 5
%html
  %head
    %title Survey Oski Admin Dashboard
    = stylesheet_link_tag 'application'
    = stylesheet_link_tag 'dashboard'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %span
      = flash[:notice]
    %nav.nav
      %ul.admin_links
        %li
          = link_to "Update permissions", admin_add_user_path
        %li
          = link_to "Test 2", "/test2"

    #main
      = yield

    %nav.nav
      %ul
        %li
          = link_to "Logout", "/logout"

app/views/layouts/devise.html.haml
/ !!! 5
/ %html
/   %head
/     %title DK Tracker Dashboard
/     = stylesheet_link_tag 'application'
/     = javascript_include_tag 'application'
/     = csrf_meta_tags

/     #main
/   %body
/     %header
/       = render 'layouts/navigation'
/     %main{:role => "main"}
/       = render 'layouts/messages'
/       = yield

app/views/layouts/volunteer_dashboard.html.haml
!!! 5
%html
  %head
    %title DK Tracker Dashboard
    = stylesheet_link_tag 'application'
    = stylesheet_link_tag 'dashboard'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %nav.nav
      %ul
        %li
          = link_to "Volunteers!", "/test1"

    #main
      = yield

    %nav.nav
      %ul
        %li
          = link_to "Logout", "/logout"

app/views/layouts/volunteer_login.haml
!!! 5
%html
  %head
    %title DK Tracker Dashboard
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags


    #main
      = yield

app/views/layouts/volunteer_login.html.haml
!!! 5
%html
  %head
    %title DK Tracker Dashboard
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags


    #main
      = yield

app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies

%span=flash[:notice]
= form_tag movies_path, :method => :get, :id => :ratings_form  do
  Include: 
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", 1, @rating_checkboxes[rating]
  =hidden_field_tag :sortBy, @sortBy
  = submit_tag 'Refresh', :id => :ratings_submit
%table#movies
  %thead
    %tr
      %th{ :class => ('hilite' if @sortBy == :title) }
        = link_to 'Movie Title', movies_path(:sortBy => :title, :ratings => @ratings_passthrough), :id => :title_header
      %th{ :class => ('hilite' if @sortBy == :rating) }
        = link_to 'Rating', movies_path(:sortBy => :rating, :ratings => @ratings_passthrough) 
      %th{ :class => ('hilite' if @sortBy == :release_date) }
        = link_to 'Release Date', movies_path(:sortBy => :release_date, :ratings => @ratings_passthrough), :id => :release_date_header
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)
        
= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description
= link_to 'Find Movies With Same Director', similar_path(@movie)
%br
%br
= link_to 'Edit', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', movies_path

app/views/movies/similar.haml
%h1 Similar Movies


%table#movies
  %thead
    %tr
      %th{ :class => ('hilite' if @sortBy == :title) }
        = link_to 'Movie Title', movies_path(:sortBy => :title, :ratings => @ratings_passthrough), :id => :title_header
      %th{ :class => ('hilite' if @sortBy == :rating) }
        = link_to 'Rating', movies_path(:sortBy => :rating, :ratings => @ratings_passthrough) 
      %th{ :class => ('hilite' if @sortBy == :release_date) }
        = link_to 'Release Date', movies_path(:sortBy => :release_date, :ratings => @ratings_passthrough), :id => :release_date_header
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)